VideoStreamingAspMvc/Models/Video.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VideoStreamingAspMvc.Models
{
    public class Video
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public string VideoFileName { get; set; }
        public string ImageFileName { get; set; }
        public int Length { get; set; }         // in minutes

        public VideoGenre Genre { get; set; }
    }

    public enum VideoGenre
    {
        Comedy = 1,
        Horror,
        Scifi,
        Romance,
        Documentary,
        Action,
        Fantasy,
        Sport,
        Kids
    }
}

VideoStreamingAspMvc/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoStreamingAspMvc.Models;
using System.IO;
using System.Diagnostics;

namespace VideoStreamingAspMvc.Controllers
{
    public class VideoUploadControl
    {
        public bool isMergeControl { get; set; }
        public string fileName { get; set; }
        public int numChunks { get; set; }
        public int videoId { get; set; }
    }

    public class VideosController : Controller
    {
        private ApplicationDbContext _dbContext;

        public VideosController()
        {
            _dbContext = new ApplicationDbContext();
        }

        // GET: Videos
        public ActionResult Index()
        {
            List<Video> videos = _dbContext.Videos.ToList();
            return View(videos);
        }


        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SubmitNew(Video video)
        {
            _dbContext.Videos.Add(video);
            _dbContext.SaveChanges();

            return RedirectToAction("UploadVideo", new { id = video.Id });
        }


        public ActionResult UploadVideo(int id)
        {
            Video video = _dbContext.Videos.SingleOrDefault(v => v.Id == id); // linq-library db query

            if (video == null)
                return HttpNotFound(String.Format("Video with id {0} not found", id));  // video doesn't exist in db

            return View(video);
        }

        [HttpPost]
        public JsonResult UploadControl(VideoUploadControl fileInfo)
        {
            string chunksDirPath, mergeDirPath;
            getVideoDirPaths(fileInfo.fileName, fileInfo.videoId, out chunksDirPath, out mergeDirPath);

            if (fileInfo.isMergeControl) {  // all file chunks uploaded; time to merge and process
                string mergedFilePath;
                if (mergeFileChunks(fileInfo, chunksDirPath, mergeDirPath, out mergedFilePath))
                {
                    processVideo(mergedFilePath, fileInfo);
                    return Json(String.Format("server: merge successful upload of file {0}, video {1}", fileInfo.fileName, fileInfo.videoId));
                }
                else
                    return Json(String.Format("server: error for merging upload of file {0}, video {1}", fileInfo.fileName, fileInfo.videoId));
            }
            else // file chunks about to be uploaded create upload directory
            {
                if (Directory.Exists(chunksDirPath))
                    Directory.Delete(chunksDirPath, true);  // TODO: do we really want this
                Directory.CreateDirectory(chunksDirPath);
                return Json(String.Format("server: start upload control message for upload of file {0}, video {1}", fileInfo.fileName, fileInfo.videoId));
            }
        }

        [HttpPost]
        public JsonResult UploadVideoChunkAjax()
        {
            HttpPostedFileBase chunk = Request.Files[0];

            string videoFileName;
            int id, chunkCount, chunkNo;
            if (!ExtractInfoFromFileChunkName(chunk.FileName, out videoFileName, out id, out chunkCount, out chunkNo))
                return Json(String.Format("file chunk has invalid name"));

            if (chunk == null || chunk.ContentLength == 0)
                return Json(String.Format("no file uploaded"));

            Video video = _dbContext.Videos.SingleOrDefault(v => v.Id == id);
            if (video == null)
                return Json(String.Format("Video with id {0} not found", id));

            string chunksDirPath, mergeDirPath;
            getVideoDirPaths(videoFileName, id, out chunksDirPath, out mergeDirPath);

            string chunkName = getChunkName(chunkNo, chunkCount);
            string chunkPath = Path.Combine(chunksDirPath, chunkName);
            chunk.SaveAs(chunkPath);
            return Json(String.Format("server: file {0} uploaded successfully for video {1}", chunkName, id));
        }

        private bool mergeFileChunks(VideoUploadControl info, string chunksDirPath, string mergeDirPath, out string mergedFilePath) {
            string[] chunkPaths = new string[info.numChunks];
            mergedFilePath = "";
            for (int i = 0; i < info.numChunks; ++i)
            {
                string chunkName = getChunkName(i + 1, info.numChunks);
                string chunkPath = Path.Combine(chunksDirPath, chunkName);
                if (!System.IO.File.Exists(chunkPath))
                    return false;
                chunkPaths[i] = chunkPath;
            }

            /*
            if (Directory.Exists(mergeDirPath))
                Directory.Delete(mergeDirPath, true);  // TODO: do we really want this
            Directory.CreateDirectory(mergeDirPath);
            */
            if (!Directory.Exists(mergeDirPath))
                Directory.CreateDirectory(mergeDirPath);

            mergedFilePath = Path.Combine(mergeDirPath, info.fileName);
            try
            {
                using (FileStream mergeStream = new FileStream(mergedFilePath, FileMode.Create))
                    for (int i = 0; i < info.numChunks; ++i)
                    {
                        using (FileStream chunkStream = new FileStream(chunkPaths[i], FileMode.Open))
                            chunkStream.CopyTo(mergeStream);
                    }
            }
            catch (IOException e)
            {
                throw e;
            }
            return true;
        }

        // to do this async?
        private void processVideo(string videoPath, VideoUploadControl info) {
            Video video = _dbContext.Videos.SingleOrDefault(v => v.Id == info.videoId); // linq-library db query
            if (video == null)
                return;

            string processedDirPath, processedDirUrl;
            getSourceUrlDir(info.fileName, info.videoId, out processedDirPath, out processedDirUrl);
            string videoBaseName = Path.GetFileNameWithoutExtension(info.fileName);
            string fileExtension = ".mp4";
            string processedVideoPath = Path.Combine(processedDirPath, videoBaseName + fileExtension);

            if (System.IO.File.Exists(processedVideoPath))
            {
                System.IO.File.Delete(processedVideoPath);
            }

            // TODO video processing with ffmpeg (extract thumbnail) async
            try
            {
                Directory.CreateDirectory(processedDirPath);
                Process proc = new Process
                {
                    StartInfo = new ProcessStartInfo
                    {
                        WorkingDirectory = processedDirPath,
                        FileName = "C:\\ffmpeg\\bin\\ffmpeg.exe",
                        Arguments = string.Format("-i {0} -c:v libx264 {1}", videoPath, processedVideoPath),
                        UseShellExecute = false,
                        RedirectStandardOutput = true,
                        RedirectStandardError = true,
                        CreateNoWindow = true,
                    }
                };
                proc.Start();
                proc.BeginErrorReadLine();
                proc.BeginOutputReadLine();

                proc.OutputDataReceived += new DataReceivedEventHandler(ffmpegStdOut);
                proc.ErrorDataReceived += new DataReceivedEventHandler(ffmpegStdErr);

                proc.WaitForExit();
                /*
                while (!proc.StandardOutput.EndOfStream || !proc.StandardError.EndOfStream)
                {
                    if (!proc.StandardOutput.EndOfStream)
                    {
                        string line = proc.StandardOutput.ReadToEnd();
                        Console.WriteLine("stdout: " + line);
                        Debug.WriteLine(line);
                    }
                    if (!proc.StandardError.EndOfStream)
                    {
                        string line = proc.StandardError.ReadToEnd();
                        Console.WriteLine("stderr: " + line);
                        Debug.WriteLine(line);
                    }
                }

                // TODO: Check that path.combine does what we want here
                video.VideoFileName = Path.Combine(processedDirUrl, "vid.mp4");
                video.ImageFileName = Path.Combine(processedDirUrl, "img.jpg");
                video.Length = 20;  // TODO
                _dbContext.SaveChanges();
                */
            }
            catch (Exception e) {
                Debug.WriteLine("```````````````````````Exception Caught````````````````````````````````\r\n{0}", e);
            }
        }

        private void ffmpegStdOut(object sendingProcess, DataReceivedEventArgs outLine)
        {
            Debug.WriteLine("aaa");
        }

        private void ffmpegStdErr(object sendingProcess, DataReceivedEventArgs outLine)
        {
            Debug.WriteLine("aaa");
        }

        private void getVideoDirPaths(string fileName, int videoId, out string chunksDirPath , out string mergeDirPath)
        {
            string baseFileName = Path.GetFileName(fileName);

            string storagePath = Server.MapPath("~/Storage/" + videoId + "_" + baseFileName);
            chunksDirPath = Path.Combine(storagePath, "chunks");
            mergeDirPath = Path.Combine(storagePath, "merge");
        }

        private void getSourceUrlDir(string fileName, int videoId, out string processedDirPath, out string processedDirUrl) {
            string baseFileName = Path.GetFileName(fileName);
            processedDirPath = Server.MapPath("~/Storage/" + videoId + "_" + baseFileName + "/processed/");
            processedDirUrl = "/Storage/" + videoId + "_" + baseFileName + "/processed/";
        }

        private string getChunkName(int chunkNo, int chunkCount)
        {
            return chunkNo + "-" + chunkCount; 
        }

VideoStreamingAspMvc/Views/Videos/ConfirmDelete.cshtml
@model VideoStreamingAspMvc.Models.Video

@{
    ViewBag.Title = "ConfirmDelete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="row">
    <div class="col">
        <h2 class="h2 text-center">Do you relly want to delete this video?</h2>
    </div>
</div>


<ul class="list-group">

    <li class="list-group-item list-group-item-heading text-center">
        <div class="row">
            <span class="col ext-center"> @Model.Title</span>
        </div>
    </li>

    <li class="list-group-item">
        <div class="row">
            <span class="col-xs-2"> Genre:</span>
            <span class="col-xs-10"> @Model.Genre</span>
        </div>
    </li>

    <li class="list-group-item">
        <div class="row">
            <span class="col-xs-2"> Description:</span>
            <span class="col-xs-10"> @Model.Description</span>
        </div>
    </li>

</ul>


@using (Html.BeginForm("SubmitDelete", "Videos", FormMethod.Post))
{
    <div class="row text-center">
        <input type="submit" class="btn btn-danger col-xs-5" value="Yes, Delete it" />
        @Html.ActionLink("No, back to videos", "Index", null, new { @class = "btn btn-default col-xs-4 pull-right" }) 
    </div>

    @Html.HiddenFor(m => m.Id)
}

VideoStreamingAspMvc/Views/Videos/Edit.cshtml
@model VideoStreamingAspMvc.Models.Video

@{
    ViewBag.Title = "Edit Video";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Edit <i>@String.Format("{0} (id {1})", Model.Title, Model.Id)</i></h2>

<!-- form will be posted to the "SubmitEdit" Action of the "Video" Controller -->
@using (Html.BeginForm("SubmitEdit", "Videos", FormMethod.Post, new { @class="form-horizontal", @enctype="multipart/form-data", @role="form"}))
{
    Html.RenderPartial("_VideoForm");
}

VideoStreamingAspMvc/Views/Videos/Index.cshtml
@model  IEnumerable<VideoStreamingAspMvc.Models.Video>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Videos</h2>

<p>
    @Html.ActionLink("Add Video", "New", null, new { @class = "btn btn-primary" })
</p>

<div class="container">
    <ul class="list-group">
        @foreach (var video in Model)
        {
            <li class="list-group-item">
                <div class="row">
                    <span class="col-xs-10">@video.Title (@video.Genre)</span>
                    @Html.ActionLink("Edit", "Edit", new { id = video.Id }, new { @class = "btn btn-xs btn-warning col-xs-1" })
                    @Html.ActionLink("Delete", "ConfirmDelete", new { id = video.Id }, new { @class = "btn btn-xs btn-danger col-xs-1" })
                </div>
            </li>
        }
    </ul>
</div>

VideoStreamingAspMvc/Views/Videos/New.cshtml
@model VideoStreamingAspMvc.Models.Video

@{
    ViewBag.Title = "New Video";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>New Video</h2>

<!-- the following line means that the form will be posted to the "SubmitNew" Action of the "Video" Controller -->
@using (Html.BeginForm("SubmitNew", "Videos", FormMethod.Post, new { @class = "form-horizontal", @enctype="multipart/form-data", @role="form"}))
{
    Html.RenderPartial("_VideoForm");
}

VideoStreamingAspMvc/Views/Videos/UploadVideo.cshtml
@model VideoStreamingAspMvc.Models.Video

@{
    ViewBag.Title = "Upload Video";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="h2">Upload Video</h2>


@using (Html.BeginForm(
    actionName: "UploadVideoChunkAjax",
    controllerName: "Videos",
    method: FormMethod.Post,
    htmlAttributes: new { @class = "form-horizontal", @enctype = "multipart/form-data", @role = "form", @id = "theForm" }))
{
    <div class="form-group row">
        <div class="col-sm-offset-2">
            <div class="file-control-wide">
                <label class="btn btn-default text-center" for="videoFile">
                    <input id="videoFile" name="videoFile" type="file" style="display:none"
                        onchange="videoFileSelected(this)" />
                    Browse
                </label>
                <input type="text" class="file-control-text" id="fileNameLabel" disabled />
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.HiddenFor(m => m.Id)

        <div class="col-sm-offset-2">
            <button type="button" class="btn btn-primary" onclick="uploadVideo(); return false;">Upload</button>
            @Html.ActionLink("Save Without Video", "Index", "Videos", new { @class = "btn btn-default" })
        </div>
    </div>
}


@section scripts {
    <script type="text/javascript">

        function videoFileSelected(fileInput) {
            let file = fileInput.files[0];
            if (file)
                $("#fileNameLabel").val(file.name); // update fileNameLabel
        }

        function uploadVideo() {
            let fileInput = $("#videoFile")[0];
            let file = fileInput.files[0]

            let maxFileSize = 4 * 1024 * 1024 * 1024; // 4GB
            if (!file || file.size == 0 || file.size > maxFileSize) {
                console.log("empty/no file uploaded, or file size too large (larger than 4GB)");
                console.log("try uploading a non empty file not greater than 4GB in size");
                return;
            }
            uploadVideoXhr(file);
        }

        function uploadVideoXhr(file) {
            let regChunkSize = 50 * 1024 * 1024; // split file into 50mb chunks
            let numRegChunks = Math.trunc(file.size / regChunkSize);
            let numChunks = numRegChunks;
            let lastChunkSize = file.size - (numRegChunks * regChunkSize);
            if (lastChunkSize > 0)
                numChunks = numRegChunks + 1;
            // create upload tasks 
            let chunkUploadTasks = [];
            // can't push in naked promises since promises start executing as soon as they're created
            // <see:https://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html advanced mistake #3>
            for (let i = 0; i < numRegChunks; i++)
                chunkUploadTasks.push((resolve, reject) =>
                    uploadChunkXhr(file, i * regChunkSize, (i + 1) * regChunkSize, i + 1, numChunks, resolve, reject)
                );
            if (lastChunkSize > 0)
                chunkUploadTasks.push( (resolve, reject) =>
                    uploadChunkXhr(file, file.size-lastChunkSize, file.size, numChunks, numChunks, resolve, reject)
                );

            Promise.resolve()
                .then(() => {
                    console.log("sending start upload control message");
                    return new Promise((resolve, reject) =>
                        sendControlXhr(false, file, numChunks, resolve, reject)
                    );
                }).then(() => {
                    console.log("chunks uploading");
                    return Promise.all(chunkUploadTasks.map((task) =>
                        new Promise((resolve, reject) =>
                            task(resolve, reject)
                        )
                    ));
                }).then(() => {
                    console.log("sending merge upload control message");
                    return new Promise((resolve, reject) =>
                        sendControlXhr(true, file, numChunks, resolve, reject)
                    );
                }).catch(console.log.bind(console));
        }

        function sendControlXhr(isMergeControl, file, numChunks, resolve, reject) {
            let xhr = new XMLHttpRequest();

            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    console.log(xhr.responseText);
                    resolve("control message successfully posted")
                }
            }
            xhr.addEventListener("error", function (e) {
                console.log("error posting control message: ");
                console.log(e);
                reject("control message error: " + e);
            });
            let postUrl = "@Url.Action("UploadControl", "Videos")"
            xhr.open("POST", postUrl);
            xhr.setRequestHeader("Accept", "application/json")
            xhr.setRequestHeader("Content-type", "application/json")

            let data = JSON.stringify({
                videoId: @Model.Id, 
                filename: file.name,
                numChunks: numChunks,
                isMergeControl: isMergeControl
            });
            xhr.send(data);
        }

        function uploadChunkXhr(file, chunkStart, chunkEnd, chunkNo, numChunks, resolve, reject) {
            // file.slice doesn't actually exclude tha last byte (at chunk end)
            let chunk = file.slice(chunkStart, chunkEnd);
            let chunkName = "@Model.Id" + "-" + numChunks + "-" + chunkNo + "-" + file.name;
            let formData = new FormData();
            formData.append('file', chunk, chunkName);

            let xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    console.log(xhr.responseText);
                    resolve("chunk posted successfully done")
                }
            }
            xhr.upload.addEventListener("progress", function (e) {
                // it will never come inside here
                if (e.lengthComputable) {
                    console.log("progress:", parseInt((e.loaded / e.total) * 100) + "%", "for chunk", chunkNo, "out of", numChunks);
                }
                else
                    console.log("upload progress is not computable");
            });
            xhr.addEventListener("error", function (e) {
                console.log("upload error: ");
                console.log(e);
                reject("upload error: " + e);
            });

            let postUrl = $("#theForm").attr("action");
            xhr.open("POST", postUrl);
            xhr.send(formData);
        }
    </script>

    <script src="~/Scripts/jquery.signalR-2.2.2.js"></script>
    <script src="~/signalr/hubs"></script>

    <script>
        $(function () {
            let signalRConn = $.connection.uploadHub;
            signalRConn.client.addNewMessageToPage = function (name, message) {
                console.log("name: ", name, "message: ", message)
            }

            $.connection.hub.start().done(function () {
                signalRConn.server.send("client", "message from client");
            });
        });
    </script>
}

VideoStreamingAspMvc/Views/Videos/_VideoAjaxUploader.cshtml
@model VideoStreamingAspMvc.Models.Video

VideoStreamingAspMvc/Views/Videos/_VideoForm.cshtml
@model VideoStreamingAspMvc.Models.Video

<div class="form-group">
    @Html.LabelFor(m => m.Title, new { @class = "control-label col-sm-2" })
    @Html.TextBoxFor(m => m.Title, new { @class = "form-control col-sm-8" })
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Description, new { @class = "control-label col-sm-2" })
    @Html.TextAreaFor(m => m.Description, new { @class = "form-control col-sm-8", rows = 4 })
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Genre, new { @class = "control-label col-sm-2" })
    @Html.EnumDropDownListFor(m => m.Genre, new { @class = "form-control col-sm-8" })
</div>

<div class="form-group">
</div>

<div class="form-group">
    @Html.HiddenFor(m => m.Id)

    <div class="col-sm-offset-2">
        <input type="submit" class="btn btn-primary" value="Save and Continue" />
        @Html.ActionLink("Cancel", "Index", "Videos", new { @class="btn btn-default" })
    </div>
</div>